source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'doorkeeper', '~> 0.4.2'
gem 'versionist', '~> 0.2.0'
gem 'rabl', '~> 0.6.12'
gem "meta_search"
gem 'haml'
gem 'kaminari'
gem 'activeadmin'
gem 'formtastic', '~> 2.1.1' # Active Admin requires 2.1
gem 'thor'
gem 'oauth2'
gem "omniauth-facebook"
gem "koala", '~> 1.5.0'
# gem 'msgpack', '~> 0.4.7'

gem 'capistrano'
gem 'capistrano_colors'
gem 'rvm-capistrano'

group :development, :test do
  gem 'fabrication'
  gem 'faker'
end
