source 'https://rubygems.org'

def darwin_only(require_as)
  RUBY_PLATFORM.include?('darwin') && require_as
end

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '~> 1.3.0'
end

gem 'jquery-rails', '~> 2.1.1'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'doorkeeper', '~> 0.4.2'
gem 'versionist', '~> 0.3.1'
gem 'rabl', '~> 0.7.2'
gem "meta_search", '~> 1.1.3'
gem 'haml', '~> 3.1.7'
gem 'kaminari', '~> 0.14.1'
gem 'activeadmin', '~> 0.5.0'
gem 'formtastic', '~> 2.1.1' # Active Admin requires 2.1
gem 'thor', '~> 0.16.0'
gem 'oauth2', '~> 0.8.0'
gem "omniauth-facebook", '~> 1.4.1'
gem "koala", '~> 1.5.0'
gem 'rack-cors', :require => 'rack/cors'
# gem 'msgpack', '~> 0.4.7'

gem 'capistrano'
gem 'capistrano_colors'
gem 'rvm-capistrano'

group :development do
  gem 'pry'
  gem 'pry-rails'
end

gem 'rspec-rails', :group => [ :test, :development ]
group :test do
  gem 'guard-rspec'
  gem 'spork'
  gem 'guard-spork'
  gem 'rb-fsevent', :require => darwin_only('rb-fsevent')
  gem 'growl', :require => darwin_only('growl')
  gem 'capybara'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'factory_girl'
  gem 'ffaker'
  gem 'vcr'
  gem 'accept_values_for'
  gem 'simplecov', :require => false
  # gem 'simplecov-rcov', :require => false
end
