xcodeproj 'Bestmix.xcodeproj'

platform :ios

pod 'AFNetworking', '= 1.0RC1'
#pod 'SDURLCache', '~> 1.2'
pod do |s|
  s.name     = 'SDURLCache-git'
  s.version  = '1.2a'
  s.platform = :ios
  s.summary  = 'URLCache subclass with on-disk cache support on iPhone/iPad.'
  s.homepage = 'https://github.com/rs/SDURLCache'
  s.author   = { 'Olivier Poitrey' => 'rs@dailymotion.com' }
  s.source   = { :git => 'https://github.com/rs/SDURLCache.git', :commit => '0a8d76fc8cd2c9e01817bbcab3af37c41895cf70' }
  s.source_files = 'SDURLCache.h', 'SDURLCache.m', 'SDCachedURLResponse.h', 'SDCachedURLResponse.m'
end
pod 'JSONKit', '~> 1.4'
pod 'MBProgressHUD', '~> 0.5'
pod 'TestFlightSDK', '~> 1.1'
pod 'MessagePack', '~> 1.0.0'
pod 'ISO8601DateFormatter', '~> 0.6'
pod 'SVPullToRefresh', '~> 0.3'
pod 'Reachability', '~> 3.0.0'
pod 'MagicalRecord', '~> 2.0.3'
#pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git'
pod 'TPKeyboardAvoiding', '~> 0.0.1'
pod 'SSKeychain', '~> 0.1.4'
